# Generated by Django 3.1.2 on 2020-12-14 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20201214_1949'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('items_json', models.CharField(max_length=5000)),
                ('name', models.CharField(max_length=90)),
                ('phone', models.CharField(max_length=111)),
                ('address', models.CharField(max_length=111)),
                ('local_address', models.CharField(max_length=111)),
                ('city', models.CharField(max_length=111)),
                ('state', models.CharField(max_length=111)),
                ('pin_code', models.CharField(max_length=111)),
            ],
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
