# Generated by Django 3.1.2 on 2020-12-17 09:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20201217_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderupdate',
            name='timestamp',
            field=models.DateTimeField(verbose_name=datetime.datetime(2020, 12, 17, 9, 14, 43, 467575, tzinfo=utc)),
        ),
    ]
