# Generated by Django 3.1.2 on 2020-12-17 13:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_auto_20201217_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderupdate',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 17, 13, 23, 17, 163546, tzinfo=utc)),
        ),
    ]
