# Generated by Django 3.1.2 on 2020-12-22 16:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_auto_20201222_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderupdate',
            name='timestamp',
            field=models.DateField(verbose_name=datetime.datetime(2020, 12, 22, 16, 52, 29, 116502)),
        ),
    ]
