# Generated by Django 3.1.2 on 2020-12-14 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_orders'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='email',
            new_name='phone',
        ),
    ]
