# Generated by Django 3.1.2 on 2020-12-22 16:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_auto_20201222_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderupdate',
            name='timestamp',
            field=models.DateTimeField(verbose_name=django.utils.timezone.now),
        ),
    ]
